export const DSL_ERROR = {
  INVALID_DSL_VERSION: 'INVALID_DSL_VERSION',
  INVALID_YAML_SUBSET: 'INVALID_YAML_SUBSET',
  INVALID_TOP_LEVEL_SHAPE: 'INVALID_TOP_LEVEL_SHAPE',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  UNKNOWN_NODE_TYPE: 'UNKNOWN_NODE_TYPE',
  INVALID_NODE_SHAPE: 'INVALID_NODE_SHAPE',
  DUPLICATE_NODE_ID: 'DUPLICATE_NODE_ID',
  UNSUPPORTED_FIELD: 'UNSUPPORTED_FIELD',
  INVALID_INPUT_SPEC: 'INVALID_INPUT_SPEC',
  EMPTY_BRANCH_BODY: 'EMPTY_BRANCH_BODY',
  INVALID_ENUM_VALUE: 'INVALID_ENUM_VALUE',
} as const

export type DslErrorCode = (typeof DSL_ERROR)[keyof typeof DSL_ERROR]
