/**
 * Configuration for Docker file generation.
 */
export interface DockerConfig {
  projectName: string
  nodeVersion?: string
  port?: number
  includePostgres?: boolean
}

const DEFAULT_NODE_VERSION = '20'
const DEFAULT_PORT = 4000

/**
 * Generate a multi-stage Dockerfile for a DzipAgent project.
 *
 * Uses a builder stage for compilation and a slim runner stage
 * with a non-root user for production.
 */
export function generateDockerfile(config: DockerConfig): string {
  const nodeVersion = config.nodeVersion ?? DEFAULT_NODE_VERSION
  const port = config.port ?? DEFAULT_PORT

  return `# ${config.projectName} — Generated by DzipAgent
FROM node:${nodeVersion}-alpine AS builder
WORKDIR /app
COPY package.json yarn.lock* package-lock.json* ./
RUN npm install --frozen-lockfile 2>/dev/null || npm install
COPY . .
RUN npm run build

FROM node:${nodeVersion}-alpine AS runner
WORKDIR /app
RUN addgroup -g 1001 -S appgroup && adduser -S appuser -u 1001 -G appgroup
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json .
RUN npm install --omit=dev
USER appuser
EXPOSE ${port}
CMD ["node", "dist/index.js"]
`
}

/**
 * Generate a docker-compose.yml for the project.
 *
 * Includes the app service and optionally a Postgres service.
 */
export function generateDockerCompose(config: DockerConfig): string {
  const port = config.port ?? DEFAULT_PORT
  const lines: string[] = [
    `# ${config.projectName} — Generated by DzipAgent`,
    'services:',
    '  app:',
    `    build: .`,
    `    container_name: ${config.projectName}`,
    `    ports:`,
    `      - "${port}:${port}"`,
    `    environment:`,
    `      - NODE_ENV=production`,
    `      - PORT=${port}`,
  ]

  if (config.includePostgres) {
    lines.push(
      `      - DATABASE_URL=postgresql://forge:forge@postgres:5432/${config.projectName}`,
      '    depends_on:',
      '      postgres:',
      '        condition: service_healthy',
      '',
      '  postgres:',
      '    image: postgres:16-alpine',
      '    container_name: postgres',
      '    environment:',
      '      - POSTGRES_USER=forge',
      '      - POSTGRES_PASSWORD=forge',
      `      - POSTGRES_DB=${config.projectName}`,
      '    ports:',
      '      - "5432:5432"',
      '    volumes:',
      '      - pgdata:/var/lib/postgresql/data',
      '    healthcheck:',
      '      test: ["CMD-SHELL", "pg_isready -U forge"]',
      '      interval: 5s',
      '      timeout: 5s',
      '      retries: 5',
      '',
      'volumes:',
      '  pgdata:',
    )
  }

  return lines.join('\n') + '\n'
}

/**
 * Generate a standard .dockerignore file.
 */
export function generateDockerignore(): string {
  return `node_modules
.git
dist
.env
.env.*
*.tsbuildinfo
.DS_Store
coverage
.nyc_output
`
}
