import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts", "src/knowledge/index.ts"],
  format: ["esm"],
  dts: false,
  clean: true,
  sourcemap: true,
  target: "node20",
  outDir: "dist",
  external: [
    "pg",
    "pg-pool",
    "events",
    "stream",
    "net",
    "tls",
    "crypto",
    "dns",
    "fs",
    "path",
    "os",
    "string_decoder",
    "buffer",
    "util",
    "@langchain/core",
    "@langchain/core/embeddings",
    "@langchain/core/language_models/chat_models",
    "@langchain/core/messages",
    "@langchain/langgraph",
    "@langchain/langgraph-checkpoint-postgres",
    "@langchain/langgraph-checkpoint-postgres/store",
  ],
});
