import { randomUUID } from 'node:crypto'
import { ForgeError } from '@dzupagent/core'

import type {
  AdapterConfig,
  AdapterProviderId,
  AgentCLIAdapter,
  AdapterCapabilityProfile,
  AgentEvent,
  AgentInput,
  HealthStatus,
  EnvFilterConfig,
  InteractionPolicy,
} from '../types.js'
import { isBinaryAvailable, spawnAndStreamJsonl } from '../utils/process-helpers.js'
import type { SpawnJsonlOptions } from '../utils/process-helpers.js'
import { InteractionResolver } from '../interaction/interaction-resolver.js'
import type { InteractionKind } from '../interaction/interaction-detector.js'

/** Default patterns for sensitive env vars that should not leak to child processes */
const DEFAULT_SENSITIVE_PATTERNS: RegExp[] = [
  /SECRET/i,
  /PASSWORD/i,
  /PRIVATE_KEY/i,
  /^DATABASE_URL$/i,
  /^JWT_SECRET$/i,
  /^COOKIE_SECRET$/i,
  /TOKEN(?!_LIMIT|_COUNT|S_PER)/i,
]

/**
 * Filter sensitive environment variables based on the provided config.
 *
 * Removes entries whose keys match any blocked pattern, unless the key
 * is explicitly listed in `allowedVars`. Returns a new object; does not
 * mutate the input.
 */
export function filterSensitiveEnvVars(
  env: Record<string, string>,
  config?: EnvFilterConfig,
): Record<string, string> {
  if (config?.disableFilter) {
    return { ...env }
  }
  const patterns = [
    ...DEFAULT_SENSITIVE_PATTERNS,
    ...(config?.blockedPatterns ?? []),
  ]
  const allowed = new Set(config?.allowedVars ?? [])
  const result: Record<string, string> = {}
  for (const key of Object.keys(env)) {
    if (!allowed.has(key) && patterns.some((p) => p.test(key))) {
      continue
    }
    const val = env[key]
    if (val !== undefined) result[key] = val
  }
  return result
}

interface NormalizedAdapterError {
  message: string
  code?: string | undefined
  original: unknown
}

/**
 * Shared base class for CLI-backed adapters (Gemini/Qwen/Crush).
 *
 * Centralizes:
 * - process spawn + JSONL stream loop
 * - started/completed/failed lifecycle events
 * - abort composition and interrupt behavior
 * - common health-check + configuration updates
 */
export abstract class BaseCliAdapter implements AgentCLIAdapter {
  readonly providerId: AdapterProviderId

  protected config: AdapterConfig
  private currentAbortController: AbortController | null = null

  constructor(providerId: AdapterProviderId, config: AdapterConfig = {}) {
    this.providerId = providerId
    this.config = { ...config }
  }

  async *execute(input: AgentInput): AsyncGenerator<AgentEvent, void, undefined> {
    const sessionId = randomUUID()
    const startTime = Date.now()

    await this.assertReady()

    yield {
      type: 'adapter:started',
      providerId: this.providerId,
      sessionId,
      timestamp: startTime,
      prompt: input.prompt,
      systemPrompt: input.systemPrompt,
      model: this.config.model,
      workingDirectory: input.workingDirectory ?? this.config.workingDirectory,
      isResume: !!input.resumeSessionId,
      ...(input.correlationId ? { correlationId: input.correlationId } : {}),
    }

    this.currentAbortController = new AbortController()
    const combinedSignal = input.signal
      ? AbortSignal.any([this.currentAbortController.signal, input.signal])
      : this.currentAbortController.signal

    const args = this.buildArgs(input)
    const env = this.buildEnv()

    // Set up interaction handling
    const policy = this.resolveInteractionPolicy(input)
    const resolver = policy.mode !== 'auto-approve' ? new InteractionResolver(policy) : null
    // Events generated by the stdinResponder closure are drained before each record
    const pendingEvents: AgentEvent[] = []

    const spawnOpts: SpawnJsonlOptions = {
      cwd: input.workingDirectory ?? this.config.workingDirectory,
      env,
      signal: combinedSignal,
      timeoutMs: this.config.timeoutMs,
    }

    if (resolver) {
      spawnOpts.stdinResponder = async (
        _record: Record<string, unknown>,
        question: string,
        kind: InteractionKind,
      ): Promise<string | null> => {
        const interactionId = randomUUID()
        const timeoutMs = policy.askCaller?.timeoutMs ?? 60_000
        const now = Date.now()

        if (policy.mode === 'ask-caller') {
          pendingEvents.push({
            type: 'adapter:interaction_required',
            providerId: this.providerId,
            interactionId,
            question,
            kind,
            timestamp: now,
            expiresAt: now + timeoutMs,
            ...(input.correlationId ? { correlationId: input.correlationId } : {}),
          })
        }

        const result = await resolver.resolve({ interactionId, question, kind })

        pendingEvents.push({
          type: 'adapter:interaction_resolved',
          providerId: this.providerId,
          interactionId,
          question,
          answer: result.answer,
          resolvedBy: result.resolvedBy,
          timestamp: Date.now(),
          ...(input.correlationId ? { correlationId: input.correlationId } : {}),
        })

        return result.answer
      }
    }

    try {
      let hasCompleted = false
      let hasFailed = false

      for await (const record of spawnAndStreamJsonl(this.getBinaryName(), args, spawnOpts)) {
        // Drain any interaction events accumulated during stdinResponder
        for (const evt of pendingEvents.splice(0)) {
          yield evt
        }

        const event = this.mapProviderEvent(record, sessionId)
        if (!event) continue

        if (input.correlationId) {
          ;(event as unknown as Record<string, unknown>).correlationId = input.correlationId
        }

        if (event.type === 'adapter:completed') {
          hasCompleted = true
        }
        if (event.type === 'adapter:failed') {
          hasFailed = true
        }
        yield event
      }

      // Drain any remaining interaction events
      for (const evt of pendingEvents.splice(0)) {
        yield evt
      }

      if (!hasCompleted && !hasFailed) {
        yield {
          type: 'adapter:completed',
          providerId: this.providerId,
          sessionId,
          result: '',
          durationMs: Date.now() - startTime,
          timestamp: Date.now(),
          ...(input.correlationId ? { correlationId: input.correlationId } : {}),
        }
      }
    } catch (err: unknown) {
      const normalized = this.normalizeError(err)
      yield {
        type: 'adapter:failed',
        providerId: this.providerId,
        sessionId,
        error: normalized.message,
        code: normalized.code,
        timestamp: Date.now(),
        ...(input.correlationId ? { correlationId: input.correlationId } : {}),
      }

      if (this.shouldRethrow(normalized.original)) {
        throw normalized.original
      }
    } finally {
      resolver?.dispose()
      this.currentAbortController = null
    }
  }

  async *resumeSession(
    sessionId: string,
    input: AgentInput,
  ): AsyncGenerator<AgentEvent, void, undefined> {
    const modifiedInput: AgentInput = {
      ...input,
      resumeSessionId: sessionId,
    }
    yield* this.execute(modifiedInput)
  }

  interrupt(): void {
    if (this.currentAbortController) {
      this.currentAbortController.abort()
      this.currentAbortController = null
    }
  }

  async healthCheck(): Promise<HealthStatus> {
    const binary = this.getBinaryName()
    const cliAvailable = await isBinaryAvailable(binary)
    return {
      healthy: cliAvailable,
      providerId: this.providerId,
      sdkInstalled: cliAvailable,
      cliAvailable,
      lastError: cliAvailable ? undefined : this.getUnavailableBinaryMessage(binary),
    }
  }

  configure(opts: Partial<AdapterConfig>): void {
    this.config = { ...this.config, ...opts }
  }

  getCapabilities(): AdapterCapabilityProfile {
    return {
      supportsResume: true,
      supportsFork: false,
      supportsToolCalls: true,
      supportsStreaming: true,
      supportsCostUsage: true,
    }
  }

  protected getUnavailableBinaryMessage(binary: string): string {
    return `'${binary}' binary not found in PATH`
  }

  protected buildEnv(): Record<string, string> {
    const raw = filterSensitiveEnvVars(
      { ...process.env } as Record<string, string>,
      this.config.envFilter,
    )
    if (this.config.env) {
      Object.assign(raw, this.config.env)
    }
    return raw
  }

  protected normalizeError(err: unknown): NormalizedAdapterError {
    if (err instanceof Error) {
      return {
        message: err.message,
        code: ForgeError.is(err) ? err.code : undefined,
        original: err,
      }
    }
    return {
      message: String(err),
      code: undefined,
      original: err,
    }
  }

  protected shouldRethrow(err: unknown): boolean {
    return ForgeError.is(err)
  }

  protected async assertReady(): Promise<void> {
    // default: no preflight checks
  }

  /**
   * Resolve the effective interaction policy for a given input.
   * Per-call options override the adapter-level config; config overrides the default.
   */
  protected resolveInteractionPolicy(input: AgentInput): InteractionPolicy {
    const perCall = input.options?.['interactionPolicy']
    if (
      perCall !== null &&
      typeof perCall === 'object' &&
      'mode' in (perCall as object)
    ) {
      return perCall as InteractionPolicy
    }
    return this.config.interactionPolicy ?? { mode: 'auto-approve' }
  }

  protected abstract getBinaryName(): string
  protected abstract buildArgs(input: AgentInput): string[]
  protected abstract mapProviderEvent(
    record: Record<string, unknown>,
    sessionId: string,
  ): AgentEvent | undefined
}
