import type { DatabaseProvider, AuthProvider } from '../types.js'

export interface EnvExampleOptions {
  projectName: string
  database: DatabaseProvider
  auth: AuthProvider
  features: string[]
}

/**
 * Generate a .env.example file based on project configuration.
 */
export function generateEnvExample(options: EnvExampleOptions): string {
  const lines: string[] = [
    `# ${options.projectName} environment variables`,
    `# Generated by create-forgeagent`,
    '',
    '# Server',
    'PORT=4000',
    `SERVICE_NAME=${options.projectName}`,
    'NODE_ENV=development',
    '',
  ]

  // Database
  if (options.database === 'postgres') {
    lines.push(
      '# Database (PostgreSQL)',
      `DATABASE_URL=postgresql://forge:forge_secret@localhost:5432/${options.projectName}`,
      '',
    )
  } else if (options.database === 'sqlite') {
    lines.push('# Database (SQLite)', `DATABASE_URL=file:./${options.projectName}.db`, '')
  }

  // Auth
  if (options.auth === 'api-key') {
    lines.push('# Authentication', 'FORGE_API_KEY=your-forge-api-key-here', '')
  } else if (options.auth === 'jwt') {
    lines.push(
      '# Authentication (JWT)',
      'JWT_SECRET=your-jwt-secret-here',
      'JWT_EXPIRES_IN=7d',
      '',
    )
  }

  // LLM
  lines.push('# LLM Provider', 'ANTHROPIC_API_KEY=your-api-key-here', '')

  // Feature-specific vars
  if (options.features.includes('ai')) {
    lines.push(
      '# AI Features',
      'OPENAI_API_KEY=your-openai-key-here',
      'EMBEDDING_PROVIDER=openai',
      '',
    )
  }

  if (options.features.includes('billing')) {
    lines.push(
      '# Billing (Stripe)',
      'STRIPE_SECRET_KEY=sk_test_...',
      'STRIPE_WEBHOOK_SECRET=whsec_...',
      'STRIPE_PRICE_ID=price_...',
      '',
    )
  }

  if (options.features.includes('teams')) {
    lines.push('# Teams', 'MAX_TEAM_SIZE=50', '')
  }

  if (options.features.includes('dashboard')) {
    lines.push(
      '# Dashboard',
      'CORS_ORIGINS=http://localhost:3000',
      '',
    )
  }

  // Redis (if using queue features or full template)
  if (
    options.database === 'postgres' ||
    options.features.includes('ai') ||
    options.features.includes('billing')
  ) {
    lines.push('# Redis', 'REDIS_URL=redis://localhost:6379', '')
  }

  return lines.join('\n')
}
