/**
 * Equivalence proof against the original dzupagent implementations.
 *
 * The fixture was generated by running the four REAL source variants over
 * the corpus (see the fixture's provenance block). Every (entry, preset)
 * cell must match byte-for-byte — string and digest — except the
 * explicitly-listed divergences, each of which asserts its own replacement
 * behavior. A divergence may only exist where the source crashed or
 * returned a non-string.
 */
import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import {
  canonicalDigestHex,
  canonicalDigestPrefixed,
  canonicalize,
} from "./index.js";
import { corpus } from "./__fixtures__/corpus.js";

type Outcome =
  | { ok: true; value: string }
  | { ok: false; errorName: string; errorMessage: string };

interface FixtureCell {
  string?: Outcome;
  digest?: Outcome;
}

const fixture = JSON.parse(
  readFileSync(
    new URL("./__fixtures__/dzupagent-golden-vectors.json", import.meta.url),
    "utf8",
  ),
) as { results: Record<string, Record<string, FixtureCell>> };

/**
 * (entryId, preset) pairs where the extraction deliberately replaces a
 * source crash / non-string return. Every pair gets a dedicated test below;
 * the sweep skips them.
 */
const DIVERGENCES = new Set([
  "cycle::authoring-v1",
  "top-level-undefined::authoring-v1",
  "top-level-function::authoring-v1",
  "top-level-function::classification-envelope-v1",
]);

function cell(entryId: string, preset: string): FixtureCell {
  const row = fixture.results[entryId];
  const found = row?.[preset];
  if (!found) throw new Error(`missing fixture cell: ${entryId} × ${preset}`);
  return found;
}

function pinned(outcome: Outcome | undefined, label: string): Outcome {
  if (!outcome) throw new Error(`missing fixture outcome: ${label}`);
  return outcome;
}

function capture(fn: () => string): Outcome {
  try {
    return { ok: true, value: fn() };
  } catch (error) {
    const e = error as Error;
    return {
      ok: false,
      errorName: e.constructor.name,
      errorMessage: e.message,
    };
  }
}

function expectOutcome(actual: Outcome, expected: Outcome, label: string) {
  expect({ label, ...actual }).toEqual({ label, ...expected });
}

describe("golden vectors: two-way corpus/fixture pin", () => {
  it("covers exactly the fixture's entries", () => {
    expect(corpus.map((entry) => entry.id).sort()).toEqual(
      Object.keys(fixture.results).sort(),
    );
  });

  it("has the pinned corpus size", () => {
    expect(corpus).toHaveLength(26);
  });
});

describe("golden vectors: byte-identical to the dzupagent sources", () => {
  for (const entry of corpus) {
    it(`${entry.id} × idempotency-v1`, () => {
      const pins = cell(entry.id, "idempotency-v1");
      expectOutcome(
        capture(() => canonicalize(entry.make(), "idempotency-v1")),
        pinned(pins.string, `${entry.id} string`),
        `${entry.id} string`,
      );
      expectOutcome(
        capture(() => canonicalDigestHex(entry.make(), "idempotency-v1")),
        pinned(pins.digest, `${entry.id} digest`),
        `${entry.id} digest`,
      );
    });

    it(`${entry.id} × authoring-v1`, () => {
      if (DIVERGENCES.has(`${entry.id}::authoring-v1`)) return;
      const pins = cell(entry.id, "authoring-v1");
      expectOutcome(
        capture(() => canonicalize(entry.make(), "authoring-v1")),
        pinned(pins.string, `${entry.id} string`),
        `${entry.id} string`,
      );
      expectOutcome(
        capture(() => canonicalDigestPrefixed(entry.make(), "authoring-v1")),
        pinned(pins.digest, `${entry.id} digest`),
        `${entry.id} digest`,
      );
    });

    it(`${entry.id} × classification-envelope-v1`, () => {
      if (DIVERGENCES.has(`${entry.id}::classification-envelope-v1`)) return;
      const pins = cell(entry.id, "classification-envelope-v1");
      expectOutcome(
        capture(() =>
          canonicalDigestPrefixed(entry.make(), "classification-envelope-v1"),
        ),
        pinned(pins.digest, `${entry.id} digest`),
        `${entry.id} digest`,
      );
    });

    it(`${entry.id} × compile-evidence-v1`, () => {
      const pins = cell(entry.id, "compile-evidence-v1");
      expectOutcome(
        capture(() =>
          canonicalDigestPrefixed(entry.make(), "compile-evidence-v1"),
        ),
        pinned(pins.digest, `${entry.id} digest`),
        `${entry.id} digest`,
      );
    });
  }
});

describe("golden vectors: listed divergences (source crashed or returned a non-string)", () => {
  it("authoring-v1 throws a TypeError on cycles (source: stack overflow)", () => {
    expect(
      pinned(cell("cycle", "authoring-v1").string, "cycle string"),
    ).toMatchObject({ ok: false, errorName: "RangeError" });
    const cyclic: Record<string, unknown> = { a: 1 };
    cyclic.self = cyclic;
    expect(() => canonicalize(cyclic, "authoring-v1")).toThrowError(
      new TypeError("cannot canonicalize a cyclic value"),
    );
  });

  it("authoring-v1 throws on top-level undefined (source: returned undefined)", () => {
    expect(
      pinned(
        cell("top-level-undefined", "authoring-v1").string,
        "top-level-undefined string",
      ),
    ).toMatchObject({ ok: false });
    expect(() => canonicalize(undefined, "authoring-v1")).toThrowError(
      new TypeError("cannot canonicalize `undefined` at the top level"),
    );
  });

  it("authoring-v1 throws on a top-level function (source: returned undefined)", () => {
    expect(() => canonicalize(() => 1, "authoring-v1")).toThrowError(
      new TypeError(
        "cannot canonicalize a function or symbol value at the top level",
      ),
    );
  });

  it("classification-envelope-v1 throws on a top-level function (source: digest of undefined)", () => {
    expect(
      pinned(
        cell("top-level-function", "classification-envelope-v1").digest,
        "top-level-function digest",
      ),
    ).toMatchObject({ ok: false, errorName: "TypeError" });
    expect(() =>
      canonicalize(() => 1, "classification-envelope-v1"),
    ).toThrowError(
      new TypeError(
        "cannot canonicalize a function or symbol value at the top level",
      ),
    );
  });
});
