import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/stable.ts',
    'src/advanced.ts',
    'src/memory-ipc.ts',
    'src/facades/index.ts',
    'src/facades/quick-start.ts',
    'src/facades/memory.ts',
    'src/facades/orchestration.ts',
    'src/facades/security.ts',
  ],
  format: ['esm'],
  dts: { compilerOptions: { composite: false, exactOptionalPropertyTypes: false } },
  clean: true,
  sourcemap: true,
  target: 'node20',
  outDir: 'dist',
  external: [
    '@dzupagent/memory',
    '@dzupagent/context',
    '@langchain/core',
    'pg',
    'pg-pool',
    'events',
    'stream',
    'net',
    'tls',
    'crypto',
    'dns',
    'fs',
    'path',
    'os',
    'string_decoder',
    'buffer',
    'util',
  ],
})
