import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/stable.ts',
    'src/advanced.ts',
    'src/facades/index.ts',
    'src/facades/quick-start.ts',
    'src/facades/orchestration.ts',
    'src/facades/security.ts',
    'src/vectordb/index.ts',
    // MC-006 subpath entry points
    'src/events.ts',
    'src/llm.ts',
    'src/tools.ts',
    'src/identity.ts',
    'src/persistence.ts',
    'src/plugins.ts',
    'src/pipeline.ts',
    'src/mcp/index.ts',
    'src/model.ts',
    'src/utils.ts',
  ],
  format: ['esm'],
  dts: { compilerOptions: { composite: false, exactOptionalPropertyTypes: false } },
  clean: true,
  sourcemap: true,
  target: 'node20',
  outDir: 'dist',
  external: [
    '@dzupagent/memory',
    '@dzupagent/context',
    '@langchain/core',
    'pg',
    'pg-pool',
    'events',
    'stream',
    'net',
    'tls',
    'crypto',
    'dns',
    'fs',
    'path',
    'os',
    'string_decoder',
    'buffer',
    'util',
  ],
})
