/**
 * Built-in SkillPack definitions for common feature categories.
 */
import type { SkillPack } from './skill-packs-types.js'

export const BUILT_IN_PACKS: SkillPack[] = [
  {
    id: 'auth-pack-v1',
    name: 'Authentication Pack',
    description: 'Best practices for authentication and session management',
    featureCategory: 'authentication',
    version: '1.0.0',
    entries: [
      {
        type: 'skill',
        content: 'Always validate email format and password strength with Zod before processing',
        category: 'validation',
        scope: ['gen_backend', 'auth'],
        confidence: 0.95,
      },
      {
        type: 'skill',
        content: 'Use httpOnly, secure, sameSite cookies for session tokens',
        category: 'security',
        scope: ['gen_backend', 'auth'],
        confidence: 0.95,
      },
      {
        type: 'skill',
        content: 'Implement rate limiting on login/register endpoints (max 5 attempts per minute)',
        category: 'security',
        scope: ['gen_backend', 'auth'],
        confidence: 0.9,
      },
      {
        type: 'rule',
        content: 'Never store plaintext passwords — always use bcrypt or argon2',
        category: 'security',
        scope: ['gen_backend', 'auth'],
        confidence: 1.0,
      },
      {
        type: 'rule',
        content: 'Include CSRF token validation on all state-changing auth endpoints',
        category: 'security',
        scope: ['gen_backend', 'auth'],
        confidence: 0.95,
      },
      {
        type: 'convention',
        content: 'Auth middleware must check token expiration before route handler',
        category: 'architecture',
        scope: ['gen_backend', 'auth'],
        confidence: 0.9,
      },
    ],
  },
  {
    id: 'payments-pack-v1',
    name: 'Payments Pack',
    description: 'Best practices for payment processing and financial operations',
    featureCategory: 'payments',
    version: '1.0.0',
    entries: [
      {
        type: 'skill',
        content: 'Validate all monetary amounts as positive integers (cents) to avoid floating point issues',
        category: 'validation',
        scope: ['gen_backend', 'payments'],
        confidence: 0.95,
      },
      {
        type: 'skill',
        content: 'Wrap payment operations in database transactions with rollback on failure',
        category: 'reliability',
        scope: ['gen_backend', 'payments'],
        confidence: 0.95,
      },
      {
        type: 'rule',
        content: 'Never log full credit card numbers — mask all but last 4 digits',
        category: 'security',
        scope: ['gen_backend', 'payments'],
        confidence: 1.0,
      },
      {
        type: 'rule',
        content: 'Always verify webhook signatures before processing payment events',
        category: 'security',
        scope: ['gen_backend', 'payments'],
        confidence: 0.95,
      },
      {
        type: 'convention',
        content: 'Payment routes must require authenticated user with verified email',
        category: 'architecture',
        scope: ['gen_backend', 'payments'],
        confidence: 0.9,
      },
    ],
  },
  {
    id: 'crud-pack-v1',
    name: 'CRUD Pack',
    description: 'Best practices for CRUD API endpoints',
    featureCategory: 'crud',
    version: '1.0.0',
    entries: [
      {
        type: 'skill',
        content: 'Use Zod schemas for request body validation with descriptive error messages',
        category: 'validation',
        scope: ['gen_backend', 'crud'],
        confidence: 0.9,
      },
      {
        type: 'skill',
        content: 'Implement cursor-based pagination for list endpoints (not offset)',
        category: 'performance',
        scope: ['gen_backend', 'crud'],
        confidence: 0.85,
      },
      {
        type: 'rule',
        content: 'Always add tenant_id filter to queries in multi-tenant context',
        category: 'security',
        scope: ['gen_backend', 'crud'],
        confidence: 0.95,
      },
      {
        type: 'convention',
        content: 'CRUD routes follow REST conventions: GET /, GET /:id, POST /, PUT /:id, DELETE /:id',
        category: 'architecture',
        scope: ['gen_backend', 'crud'],
        confidence: 0.9,
      },
    ],
  },
  {
    id: 'dashboard-pack-v1',
    name: 'Dashboard Pack',
    description: 'Best practices for dashboard UI components',
    featureCategory: 'dashboard',
    version: '1.0.0',
    entries: [
      {
        type: 'skill',
        content: 'Use Pinia stores for dashboard state management with composable API',
        category: 'state',
        scope: ['gen_frontend', 'dashboard'],
        confidence: 0.9,
      },
      {
        type: 'skill',
        content: 'Implement skeleton loading states for all data-fetching components',
        category: 'ux',
        scope: ['gen_frontend', 'dashboard'],
        confidence: 0.85,
      },
      {
        type: 'rule',
        content: 'Dashboard queries must include date range filters to prevent full-table scans',
        category: 'performance',
        scope: ['gen_backend', 'dashboard'],
        confidence: 0.9,
      },
      {
        type: 'convention',
        content: 'Dashboard components use grid layout with responsive breakpoints',
        category: 'layout',
        scope: ['gen_frontend', 'dashboard'],
        confidence: 0.85,
      },
    ],
  },
  {
    id: 'realtime-pack-v1',
    name: 'Realtime Pack',
    description: 'Best practices for WebSocket and real-time communication',
    featureCategory: 'realtime',
    version: '1.0.0',
    entries: [
      {
        type: 'skill',
        content: 'Use WebSocket with heartbeat ping/pong to detect stale connections',
        category: 'reliability',
        scope: ['gen_backend', 'realtime'],
        confidence: 0.9,
      },
      {
        type: 'skill',
        content: 'Implement exponential backoff reconnection with max 5 retries',
        category: 'reliability',
        scope: ['gen_frontend', 'realtime'],
        confidence: 0.9,
      },
      {
        type: 'rule',
        content: 'Always validate WebSocket message schema before processing',
        category: 'security',
        scope: ['gen_backend', 'realtime'],
        confidence: 0.95,
      },
      {
        type: 'convention',
        content: 'WebSocket events follow namespace:action format (e.g., chat:message)',
        category: 'architecture',
        scope: ['gen_backend', 'gen_frontend', 'realtime'],
        confidence: 0.85,
      },
    ],
  },
  {
    id: 'file-upload-pack-v1',
    name: 'File Upload Pack',
    description: 'Best practices for file upload handling',
    featureCategory: 'file-upload',
    version: '1.0.0',
    entries: [
      {
        type: 'skill',
        content: 'Validate file type via magic bytes, not just extension',
        category: 'security',
        scope: ['gen_backend', 'file-upload'],
        confidence: 0.95,
      },
      {
        type: 'skill',
        content: 'Use pre-signed URLs for direct-to-storage uploads (not through API server)',
        category: 'performance',
        scope: ['gen_backend', 'file-upload'],
        confidence: 0.9,
      },
      {
        type: 'rule',
        content: 'Enforce max file size limits at both client and server level',
        category: 'security',
        scope: ['gen_backend', 'gen_frontend', 'file-upload'],
        confidence: 0.95,
      },
      {
        type: 'convention',
        content: 'Store files with UUID names, preserve original name in metadata',
        category: 'architecture',
        scope: ['gen_backend', 'file-upload'],
        confidence: 0.85,
      },
    ],
  },
]
